title = "TEST SITE"
description = "noob Rustacean"
base_url = "https://ururu.netlify.app/"

compile_sass = true
build_search_index = false

generate_rss = true
feed_filename = "rss.xml"

default_language = "en"

taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true
highlight_theme = "dracula"

[languages.en.translations]
home = "Home"
works = "Works"
posts = "Posts"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
last_page = "Last Page"

[extra.social]
github = "2vg"
twitter = "2vg"
facebook = ""
instagram = ""
dribbble = ""
weibo = ""
steam = "mikopero"

[extra.show]
tags = true
archive = true
links = true

[extra.comment.disqus]
name = "ururu"

[extra.myvar]
title = "たたかうおおかみ！"
description = "noob Rustacean"
